// <auto-generated />
namespace KASIF_CRAWLER.LAYER_DATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class KasifContextv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KasifContextv1));
        
        string IMigrationMetadata.Id
        {
            get { return "201901231714526_KasifContext-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
